#cloud-config
users:
  - name: youruser
    sudo: ALL=(NOPASSWD:ALL)
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
        - ${ssh_key}

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - curl
  - vim

# WARN: This will reboot after first boot if kernel updates
power_state:
  mode: reboot
  condition: test -f /var/run/reboot-required
